language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
  # FIREBASE_SECRET:
  - secure: NddeGWR3ETg11OxRlMrKNy1b6Dswc7DfT63ucuIcmVaG5//ttmhLG8HyIhED2jhXVIL/KRealvGKgSBbkydCw1oSxImUxuhYwiUypET0ptAZe+Q0mTpTbKPPGqXRvitLN6Swoj1skXtwAUXCCw5SRusebfY/eO6axUuTca6L3Ei9A20kkdWWgAbNwFCDWN0LADb0ohGxsD+pwa+H/aiCDOmO4oPMCga6Uuv9fm3vaq4d5aVQnbgRm1A1TnGHK24I0WY7mlIB6nc6bCpYwYGRp7RjizWq4zsgD2g7UUkityqz8VMdqZARiS0NnJsan3WsE+MfA89eUCnbOpyO2EfYiw0UAjvHf1WtlhnJoWMEJ3mtL/zrWmLAAu4Eojwsj/wcmtCfO4YPeeYhfiCsbpGSuhAWntC0AlsRLQJgqz+z2MCyiwCUVWM3+BkLZ67xIAV8SFd5IMqVcsRpcRC95O+GD0SjAajtX2MQkok4hGATKHbpysW65doY68Eg5N03VNlajdeR2LO674QARFXf5uWpwwTHLd/9DQdQx9fE5oOiQDQS/Cplr8oqIqr6OleFHHH8fLPVApoZDkQi+rgZuiy1DwrouE1Bt+k4t1WuCJJ4zOi5jMDaa7F04mBY3GKS1ioJvvBYQ+mz83y9ZSg/zj+X7qBR7nEcp/WFHImF+5XOCxI=
  # FIREBASE_TOKEN:
  - secure: T1YIwyOHxrNqzHHcvZsGBU42xbyM5iEOiEAFGzxKxN5RRIkqpMQ0Gtm0KyWdSiMjawnIP233rpxMfKOVxg0t97eae08vR3++AD7xU70HL0UCyvI7GTIJq9h/Ub2svbLI+rHaxLHFVrJJAIJYshNemGB8pNYHwWg1b//uOpOiVstR/dNG+A5JL1Y/zTtM1CMbC2ity6ZzPLPQ2ju52UYwF7dbUUm7+ECagbT6olEV1glkaVjoZD/KL7sLdeQxnwF37OeODuKMoZPA9fJIwFTZjDi/SfpqAbxlTRUgFmTDjB13zctoV9YPB1HG8gkw306NOEFkdrUQEzwjyenEKpv2dXGw37CkwHFgv0NLEaWt0pL2GqVKqLbRBBz5C9ANDB7sXIo80bDNbNbEFmPFsLrCWV/7ZH7S21JhkePcUhmShO/XtaAhDyj07BBCO48t6peN4guYf56429HB0nryYhIKwOkbdjtoKFeW0SbCBTl/eyIFrwb06QRJYsj8q+Lp0S0JHNMeKJyE3CaiSR2YyBjUwquqR+raJ2NWpmIcWCD14o1Vhy5rzdcgQzdUIqbf9o8iWBJf3VBcHUvcEApQg1zsYt3Y2T7re2yZ5iiBf14yBkeumPuYwysPyjSBSP4Op59dR+CoYtwa5HCKjdUwHI7CuK47sPKQUuwtx8aFfHHbqt0=
