language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
  # FIREBASE_SECRET:
  - secure: a6JBZw5qJizTtQ4CsaZ+UHlPpQeeMRPNXupRuTRfeDCsgqF1p7x90k9EC9cz8+NatDsYq5HJAyAcVDjxGvtFL4KQbtc35T3xAR78YT3vMWougNNGX4Ahc4kFBb6a75Yppnfr5NElgjr9kNGEXkdWmmolUlY4zXV2jRJrmkXBoJmHzMqQfHU2vGICRvuIlu2JBtBBU+O6MEpXhoDG1Y+X4x2aeHUrZ6aPtHp35jlHQLlPbOeDpc+AsQKbifBd2mxp3vGhT9uMg5voXM6dyPWmP+yEMI4WwQb2KGOl+WCPpmvfZ/UrtufcxKM6RqgZdYABViXD199rb/aL4+K55dFYcfHbpm/uAiWKJIlePJnRCqdKudRGZcr0JB6smyvZApSaNe7bX/o7uaGjCPKpkQoeFYrIW7OEdLwtwWuXRTaAlGRKZlZjAb9lk/RCgHONtan4ALufsv8fHjyzvFclEddLGTW/5/gicqJEtR+5K2RuozyZZuEy8XVax+bOvhZ2t/ay2ygVwpHWZ2GXo+BhU2FpGq+HEd9b5V/nebA6mBQK78aJFTpSl7kNdW4lm0X0HcWahqR4jhL5RLZ9YsJmw+JuiJ92DtUVbeuVKHd9Fc82tCca+qgRGz3cZXCwDfH5UxPJbUwUl+ydwsv1J2PSOFhPritwT8kggmn1VpOmx0VJYWQ=
  # FIREBASE_TOKEN:
  - secure: BX1e6SMCQyi1GEtyBshaT5l5XrKmhYonqF/T2UbiBtlQfXzDPGCqSdDFLw23T4+ldS+0ErZmchseNDbHhx0vSLhDwOif4RBgb2/AnWfszVv99p7yYE7TJSe6H3ET3iY84MAjctbXH3bZ+BxvoCK2VQM3OPpzz0jltI5UBgnRYKdlB/fo/kr8lJIbcZcknbIGlJxAzcQQTO+AdvD/lQe+ZHgDZCSbKfpNEXFe9W3YbSVUEn2CyCEqYZ5nrxBXjDsuh4RO8a32eBDxltqd9iNG/NJA+ebsxKgk3AUigLZDZPfFg5+3kHOZzBU9IzM2bSEK2K5hnW68C+HR//piSHBktr01hzODNeQVT2NwcrvXQnX2g7H7w8OLnF3H3AMiyCKKuudgq1XLJ3N3lpzluruVtH0/bxkN5QX9iFLDmZdIGx4lZay4NmVirCc+dM0XAylZaSI2eOkgVYx0GJTy6KfOh1v8VdgCJXGVcDYS3bd+cY4WY3Lvj9DBVIB40F5cSw4dHM7B2bShRDixDwAuoq5zv2GSXBLwXYTvY7iEEPzWwae7Gqu5nreA+hjowNm1eM0E+P5RlVgWhpH35BczndHHnFSVOvThqc0ZnJkJBkG9cJW0fT2i1ibMpdU+N5eguKvxw6HTx+IjwQqJWDKITzUpNVYh9yBg0DZLyt18k4hFF4s=
